language: java
jdk: oraclejdk8
sudo: false
install: true
script:
- mvn clean verify
cache:
  directories:
  - "$HOME/.m2"
deploy:
  provider: heroku
  api_key:
    secure: Sz/lnG7r9DvsWCvD0r83fMvbLSP4aMX3gFU2BvJzHMhmZ0DKD3cQFEFvFQvo3d5frH+0nt7BxoqJ4DKqmjMYqYMzeYPj0NNIBcqTOFG0sPLFWodlBMKZD1nB6UhCE5oWrGiWahC5VI31GdEd87ZBB0oKPWSHYqJBUwj3qIHGZ8WfC6Qb7h7XCoxW7l+f4tljrOQ8atKymUfVcJsZjvNIdGF27xnlqKl+17dgnXXp6jQxQNAfsi1Jbn5zkNFGRVFsIKWX6K7ug3CwQKdNLWy8dw+CrIURb2bWw0X58/Ry3dDc7YZyYXcA3H99+22OUhZGSeqtS6mYz3ZCEJh0fDrNwRKKdwtHGMc26X3gcfuXozE6uVi7JPjdsRkS+AUigxJAM5TeUfN+zVHPY/SUXOq4lUvFAxLzoDyBbR+zuet4HLufazG3XEvxNaWyyZmGmCu/Uw4q+po9GSUpgCa2Pcrv0LYvRyenFNv/By1EXXT+FgOwr0OscQBurJZausf+RtN2/bMRo5ZUdT2+YZkwZPuJGtAiRCnJfoXBE9YYbCPstudlpQ/klUhN4ZD1X3JTz5ZRk8h+29LNEQh+0IR0i3hXkmepG0yfA1QicxbLNFYyfoCFUU/y9PEAc7t1xIzyzQF07zQwmTtrIPf4OzsM09OeaDPbD3G6jewve4ehueRvwKM=
  app: sqlsheet
  on:
    repo: saturator22/sheetql-webapp
