language: java
jdk: oraclejdk8
sudo: false
install: true
script:
  - mvn -DtestSourceDirectory=src/test/java/com/codecool/service/dataManipulation test
  - mvn clean verify
cache:
  directories:
  - $HOME/.m2
