language: java
jdk: oraclejdk8
sudo: true
install: true
script:
- mvn clean verify
cache:
  directories:
  - "$HOME/.m2"
deploy:
  provider: heroku
  api_key:
    secure: aRDPyCJdnvkPpg5+P6ixghnsf8N8GJOr2Zi+UhfXw5vz4dbQkH7c2IFLai4nWXPL5aG8ggHEroaO4Z6XaqmpF5qzMRq2gepjRthrZCz6MkbPf6L1ayGRSTsppgEKMhMci+NCpwBLloZnLr/5ZAN3ZB/ZgZSEzW+nLbyrR/6WSUm/kujVsyhMK7kf5E4h5JuijtG0VuvWmPoELK6/qOnBw65faDKb0EPw48x3hJmib+TwIpGsz3q5waI5hQF4OX/UTlLylF+7Yi0txhc2Nv+/ki3/PMA0CMHArl6QLYxApj+c9A5ULPYjuIa+z0S//e8XDmC2nH3RGG6sjvO5iqJmWRSpBRlej/IvZ/xFV9IznykUu4sZn36NH8JfW68u6cvcmCwSEkFhTwUl5EfrkYHCHmYx47SZRKaUiwp1F3FpcpM8m0YlSe3Al7NgjIWMcZE2+Jnh/Sobb5DlWKFXVmiq7Krli0IubuihzDF+mj4o7IVQey/wF9N4HNKw4nJv5Ii2jY19I3AANFAgYBGScs/ee7uc6/ovvnsUWlSG3wOjEY4K0pXgd0q7WjV4f4D18BUTts1NPlennUoXZ8jNveSNwHj4E1IDisjRW7qL1HJsuSqNIeZ8tUelm0XpP9vuvpl7cUXyD4jU0lb46h6L7VEqBkOVcwAQy+awVO3mmbxzwiA=
  app: sqlsheet
  on:
    repo: saturator22/sheetql-webapp
