language: java
jdk: oraclejdk8
sudo: true
install: true
script:
- mvn clean verify
cache:
  directories:
  - "$HOME/.m2"
notifications:
  email:
    on_success: never
    on_failure: never
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: TOdFs/FbFd5t4VDlo8JTGPV41xcI+aIiTRDc8mr4xHIMRS7qeCQKKieMpknHM7yaP+kyn+8+i08mREDsxW+j1FrE4Y0lU+iTL1frGx+ZLw2SmuKcAvhGkXvYwsAaZYRxstNrmFZXzaxnOwRswii+cehtcInja92cqcC6SRP5DNdIlHAQlXwRiKWv487EOrDBIyi0merO7J5IGTCdGB2sK5ZM2V2gUJ+7pIsJyT09wNnBZCNIOj/dZhFyXKEVSxnInJG+bG9+KlRA1CIfjsxpwt4M+Wd6D0WgfKd3iORB4DKlKZUPdTp2btZmQqdQ3SBtAobMy3pBGm6n3ZWDM4HjZCqeD26hQL+/8e+2YHQpi/kWFdUI3iY7J8lxCX6jT8KEGHrUfyrT3U+QRPqmv8knQSwlQF87UzX8RItbSUVAAkeKIQGaL9gmETB0V++UZFwwrVW+eoKZuvdAiNybOej2u2480k4GfrWV9FmK/w9YZA+J55SIOLtWimmJ44gKqoDoWqAEWcn2UCPKu8Co0URB2jcdBOE51eLE+z79fk45bRlbh+KPZYMOJCz4gRtTzUM9wW6oeeG/uC69ulDOGHvQsCkUdKVGpznASZdvpLxI/RcQIcY3I92ROwWnRuWKeDC/ph9WXmzQgBZcOq8eQVTHexMZmdcAg9w6dEtdiTeIQ78=
  on:
    repo: saturator22/sheetql-webapp
  skip_cleanup: true
