language: java
jdk: oraclejdk8
sudo: false
install: true
script:
- mvn clean verify
cache:
  directories:
  - "$HOME/.m2"
deploy:
  provider: heroku
  api_key:
    secure: UZEmAcovfilLbAfXXLcz+oAmJdlSe8Nu36D845fmBounoQERcj+v5lfhP9XBoI92tzRNknNsraU2dR9oTFzUwPEG77Y3qlZv3qnofXJxx2+4t3ZzOhDhSjDzMdbqSrtQmVkgIs48b2f9nc3aDGBcKlMRo2D663oK6OqITijYRK/Welb019e9DP+efyQcFSrUf46VNBvz8L6BwEQpebN1NVEjO4z2D6GIocSuisjxi0SX2zP0hHy75g7PFW8EwqYjQALdI+KytOiyPg8ZgA40GCYd6C3yiNdpFfW1VXwPEfn+OQTZfAhDusjamczt4na2eBH/Av+8XYg9iaeEfud6qWHpt1dPjaHLB8lF/oVpn4AgshXLHrqkbrCGv29aYWKArl7s2+ccxBFoFfUTlBqrVtLcduVUS76/q65SlUeWwDuEsQ7BavZ3UHY/QZx3YW+yO8mw1gSdxaj67EJvGZ9Jerf5gzX828SfU+eUGdkJCk+myWW0bGiwmNH4EIbLJkrlGAfCKjhkNfb5FTNyVSR/KGNnIMNoU+05dgrgG95EuXYVWzt+Le//hXtEA7NB9+ywid3YcCnOZCAG/1CUUqxFegbDivd8QFh8s/AJLh94oStrTkX3wG0fO6rROOiiBQtBOlewBUmL67E3rX7KwYORcXO4l+irtJjSY61ioQUdOjg=
  app: sqlsheet
