language: java
jdk: oraclejdk8
sudo: false
install: true
script:
- mvn clean verify
cache:
  directories:
  - "$HOME/.m2"
deploy:
  provider: heroku
  api_key:
    secure: SbTpTCJSVF1KTKNqUPPBrV4YQzb+DDZCsyzZhaqRcqeaLkUBvX7c6lMfbrgZYzDu2hvF18/Y7B9VHUuU6TEgZUP5g6sPGXA6ffIbcjQwWF8YsTg2pVi4i66zLZVf1sZcA7H7WzF35qFOR0NlBXi3zLKAKdJnhCklPgENgCmAzYmegLwM6qoFz+nkTp2kO4V01ZwIinbCcDwkKImih6VB7/e4c0XjCKAcO4bHu1EaPZ0gA3rjkL5urWQzAAqjyz3c9+4VyRS8+e2QD6Q4uPbxmGFCKLh+oZyfwBVPsH360C/bmJmeI9r/Lgx3d336faE3mikiOrDRvnuCB2SXXLQ0uZDGAuzsOAz2ekNIAnkFw/ewtSn3XVRYI4uKGTHzBPJmFzptuRYZ3BvNGA47W06do2YoH9XMJOlazVq3P4dXBJ3jURtTq0TYaItDojuVU1KQhCisXgTlPht53DiNYp03ri5UDdAZdcRqU4lxGeEnURcd6Aw+H8kyscO6h0zgsUTjnEsADOSSbKPri2zbxdsN7pR6/sRLGbcRFtF6i9qA35Of6SO2Lzo/vzBC+VGH5SUCshMOs7p8yIkrV6Wy7HH+u4fkCyJreFH4si1p4ARzJBaz8ERG8nVfRtpcswJbquFvMVO8ADmH9aKnu43M7fua3Fy7Veq4n/3t5hVPLYHMD/M=
  app: sqlsheet
  on:
    repo: saturator22/sheetql-webapp
