language: java
jdk: oraclejdk8
sudo: true
install: true
script:
- mvn clean verify
cache:
  directories:
  - "$HOME/.m2"
deploy:
  provider: heroku
  api_key:
    secure: H8Zb0KVIw/Kw57gFp5ebxhBjqA00Rw9WyCBMskDN0PxsepbTvZISelvjOiMzmRsL4ZVZHdylscpFeY5BbE/nlLl3HtKkXAMaGvgibYks6k5WAD7UqlZN4g3k7gxaUtseGN5g+47mFIWoLyU05F4kHsqRcyvayaDkyms0XGoUTig4q9KXHsdECQaf1lKUj0kVjIwDF0Nr6vr3Do69JkdYdh0H82mP0/D5MkMa7sr8ARdh0jVBDS/GcwPLJ2ibZxPevdv1VxKzvuz53+Ffm1nWjvCDGLryI3TuvARywk8qokTKGapUtrUI2akopctRk6w/VSSn/+PBvt12CgTep3n3o3A1GaEiLExaUkw0dNceSrASzhpZiJzbECQYGslcO0JYUX/j6I+mwmsVpOj8YTvJMpcUvhGo3nZ+G+E83sxZaqrcdW+/UYZdnA6s3F7LTMWZ/iRmo/QqY3QdG/hnmA+pCQsr+kd0xa4MMN2jhjRD8f26rum04TQRpOcrlKVN6xpn5SpB/HTcDQ5plJj6rpcKlHX3mOzlyVfsfe+5/yXbuazmqyGw8ammrpYqmVu0X4fOPDGCvjICJEvcJKd0ITFJPEUYWqk6txA8W1Mf4msHIB9R299Lse+c4ldBqY+JcppX8d9rT8YFMyi3nIko6QCvFQpvNzZHc5HrDnrbksLvTkU=
  app: sqlsheet
  on:
    repo: saturator22/sheetql-webapp
